### PR TITLE
feat(repo,teams): Add eleven-labs.com repository

### PR DESCRIPTION
**Pull request by graillus**
## Description

Create the `eleven-labs.com` website repository on Github.com, to move away from Gitlab.com

## Breaking Changes

None

### Checklist

* [x] `terraform fmt` and `terraform validate` both work from the root directory (look in CI for an example)
* [x] Docs have been added/updated (for bug fixes/features)
* [x] Any breaking changes are noted in the breaking changes section above

### CODE REVIEW

**Review by Pouzor — APPROVED** [review]
Sounds good, I let @VEBERArnaud check if all needed is here

**Review by snroki — APPROVED** [review]

**Review by VEBERArnaud — APPROVED** [review]
LGTM

**Review by VEBERArnaud — CHANGES_REQUESTED** [review]
Stange output in the plan, further investigations needed

**Review by VEBERArnaud — APPROVED** [review]
LGTM

**Pull request merged**
